.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG\-ADMIN_CLUSTER_ZKSTART" "8" "January 2018" "Stardog Union" "stardog-admin"
.
.SH "NAME"
\fBstardog\-admin_cluster_zkstart\fR \- Starts a ZooKeeper server instance (Deprecated: Use \'zk start\' instead)\.
.
.SH "SYNOPSIS"
\fBstardog\-admin\fR \fBcluster\fR \fBzkstart\fR [ \-\-config \fIconfig file\fR ] [ \-\-foreground ] [ \-\-home \fIhome\fR ] [ {\-p | \-\-passwd} \fIpassword\fR ] [ {\-P | \-\-ask\-password} ] [ {\-u | \-\-username} \fIusername\fR ] [ {\-v | \-\-verbose} ]
.
.SH "OPTIONS"
.
.TP
\fB\-\-config\fR \fIconfig file\fR
Zookeeper config file\.
.
.TP
\fB\-\-foreground\fR
Flag to start this application in the foreground\.
.
.TP
\fB\-\-home\fR \fIhome\fR
Zookeeper home directory location\. This is where the log and other config resides\.
.
.TP
\fB\-p\fR \fIpassword\fR, \fB\-\-passwd\fR \fIpassword\fR
Password\.
.
.TP
\fB\-P\fR, \fB\-\-ask\-password\fR
Prompt for password\.
.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-username\fR \fIusername\fR
User name\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose flag that causes more detailed information to be printed
.
.SH "DISCUSSION"
In order to configure your zookeeper instance you will create a config file with the settings described in http://zookeeper\.apache\.org/doc/r3\.4\.6/zookeeperAdmin\.html\. By default the zookeeper config file is located in $STARDOG_HOME/zookeeper\.properties\. A different config file can be specified with the option \-\-config\. In order to stop the ZooKeeper process you can use \'zk stop\'\.
